# Generated by Django 6.1.1 on 2026-09-22 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('DEVIS', 'Devis'), ('FACTURE', 'Facture')], default='FACTURE', max_length=10)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('date_emission', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé / Payé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='garage.client')),
                ('reparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.reparation')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='garage.facture')),
            ],
        ),
    ]
